/**
 * FAQ content — parsed from `content/faqs.md` at build time.
 *
 * ─────────────────────────────────────────────────────────────
 * FOR LENA: do not edit this file. The questions live in
 * `content/faqs.md` and this just reads them.
 * ─────────────────────────────────────────────────────────────
 *
 * SERVER ONLY. This module touches the filesystem, so it must never be
 * imported by a `"use client"` component — the page reads the FAQs on the
 * server and passes them down as props. `import type` from here is fine
 * anywhere, since types are erased at compile time.
 */

import fs from "node:fs";
import path from "node:path";

export type FaqBlock = { type: "p"; text: string } | { type: "list"; items: string[] };

export type FaqItem = {
  /** Stable anchor id, derived from the question. */
  id: string;
  question: string;
  answer: FaqBlock[];
  /** Draft answers are visible locally and withheld from the public site. */
  draft: boolean;
  /** Service slugs this question also belongs to. */
  services: string[];
  /**
   * Optional `review: YYYY-MM-DD` for answers containing something that goes
   * stale — a rate, a threshold, a figure. Surfaced only when running locally,
   * so it nags Lena while she edits and never reaches a reader.
   */
  review?: string;
};

export type FaqCategory = {
  /**
   * Stable anchor id. Prefixed, because a category and a question can slugify
   * to the same string ("How Much Can I Borrow") and duplicate DOM ids break
   * both the anchors and the shared #question links.
   */
  id: string;
  title: string;
  items: FaqItem[];
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/['’"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Turns the answer body — everything between one `###` question and the next
 * heading — into paragraph and list blocks. Consecutive `- ` lines collapse
 * into a single list; every other run of text becomes a paragraph.
 */
function parseAnswer(lines: string[]): FaqBlock[] {
  const blocks: FaqBlock[] = [];
  let paragraph: string[] = [];
  let list: string[] = [];

  const flushParagraph = () => {
    if (paragraph.length) blocks.push({ type: "p", text: paragraph.join(" ") });
    paragraph = [];
  };
  const flushList = () => {
    if (list.length) blocks.push({ type: "list", items: list });
    list = [];
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      flushParagraph();
      flushList();
      continue;
    }
    if (trimmed.startsWith("- ")) {
      flushParagraph();
      list.push(trimmed.slice(2).trim());
      continue;
    }
    flushList();
    paragraph.push(trimmed);
  }
  flushParagraph();
  flushList();
  return blocks;
}

function parse(markdown: string): FaqCategory[] {
  const categories: FaqCategory[] = [];
  let category: FaqCategory | null = null;
  let question: string | null = null;
  let draft = false;
  let services: string[] = [];
  let review: string | undefined;
  let body: string[] = [];

  const commitQuestion = () => {
    if (!category || !question) return;
    const answer = parseAnswer(body);
    if (answer.length) {
      category.items.push({ id: slugify(question), question, answer, draft, services, review });
    }
    question = null;
    draft = false;
    services = [];
    review = undefined;
    body = [];
  };

  // The preamble above the first `---` is instructions for Lena, not content.
  const start = markdown.indexOf("\n---\n");
  const lines = (start === -1 ? markdown : markdown.slice(start + 5)).split(/\r?\n/);

  for (const line of lines) {
    if (line.startsWith("## ")) {
      commitQuestion();
      const title = line.slice(3).trim();
      category = { id: `topic-${slugify(title)}`, title, items: [] };
      categories.push(category);
      continue;
    }
    if (line.startsWith("### ")) {
      commitQuestion();
      question = line.slice(4).trim();
      continue;
    }
    if (question === null) continue;

    const status = /^status:\s*(.+)$/i.exec(line.trim());
    if (status && body.length === 0) {
      draft = status[1].trim().toLowerCase() !== "approved";
      continue;
    }
    const svc = /^services:\s*(.+)$/i.exec(line.trim());
    if (svc && body.length === 0) {
      services = svc[1]
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      continue;
    }
    const rev = /^review:\s*(.+)$/i.exec(line.trim());
    if (rev && body.length === 0) {
      review = rev[1].trim();
      continue;
    }
    if (line.trim() === "---") continue;
    body.push(line);
  }
  commitQuestion();

  return categories.filter((c) => c.items.length > 0);
}

const SOURCE = path.join(process.cwd(), "content", "faqs.md");

const isDev = process.env.NODE_ENV === "development";

let cached: FaqCategory[] | null = null;

/**
 * Read and parse the source file.
 *
 * Cached in production — the content is fixed at build time. NOT cached in
 * development: Next has no idea a markdown file is a dependency of this
 * module, so a module-level parse would go stale the moment Lena edits
 * faqs.md and she would have to restart the dev server to see her own words.
 */
function all(): FaqCategory[] {
  if (isDev) return parse(fs.readFileSync(SOURCE, "utf8"));
  cached ??= parse(fs.readFileSync(SOURCE, "utf8"));
  return cached;
}

/**
 * Categories with their questions. Drafts are included when running locally so
 * Lena can read them in place, and stripped everywhere else.
 */
export function faqCategories(): FaqCategory[] {
  const categories = all();
  if (isDev) return categories;
  // Drafts and review dates are both editorial state — neither belongs in
  // anything a reader can see or a crawler can index.
  return categories
    .map((c) => ({
      ...c,
      items: c.items
        .filter((i) => !i.draft)
        .map((i) => ({ id: i.id, question: i.question, answer: i.answer, draft: i.draft, services: i.services })),
    }))
    .filter((c) => c.items.length > 0);
}

/** Flat list, in page order. */
export function faqItems(): FaqItem[] {
  return faqCategories().flatMap((c) => c.items);
}

/** The questions tagged for one service page. */
export function faqsForService(slug: string): FaqItem[] {
  return faqItems().filter((i) => i.services.includes(slug));
}

/** Answer flattened to a single string — for FAQPage structured data. */
export function faqPlainAnswer(item: FaqItem): string {
  return item.answer
    .map((b) => (b.type === "p" ? b.text : b.items.join(". ")))
    .join(" ");
}
