import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/build-affordability-check.mjs from the original
    // standalone calculator — lifted verbatim, so not ours to lint.
    "scripts/_*.mjs",
    ".local/**"
  ]),
  {
    rules: {
      // `>` and `}` in JSX text read as stray syntax and are worth flagging.
      // Quotes are not: JSX needs no escaping for them, and `&apos;` is
      // strictly harder to read than `'`. Apostrophe style is a typography
      // decision — see DECISIONS.md.
      "react/no-unescaped-entities": ["error", { forbid: [">", "}"] }],
    },
  },
]);

export default eslintConfig;
